"""user last name column fix

Revision ID: 727ea1cb1b9c
Revises: 1252c9d19d7d
Create Date: 2025-09-20 03:47:41.714409

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "727ea1cb1b9c"
down_revision: Union[str, Sequence[str], None] = "1252c9d19d7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    # ### end Alembic commands ###
