"""Note author_id column rename

Revision ID: 9974d6bafcb0
Revises: 727ea1cb1b9c
Create Date: 2025-09-22 01:26:38.242465

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9974d6bafcb0"
down_revision: Union[str, Sequence[str], None] = "727ea1cb1b9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notes", sa.Column("author_id", sa.Integer(), nullable=False))
    op.drop_constraint(op.f("notes_user_id_fkey"), "notes", type_="foreignkey")
    op.create_foreign_key(None, "notes", "users", ["author_id"], ["id"])
    op.drop_column("notes", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notes", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "notes", type_="foreignkey")
    op.create_foreign_key(
        op.f("notes_user_id_fkey"), "notes", "users", ["user_id"], ["id"]
    )
    op.drop_column("notes", "author_id")
    # ### end Alembic commands ###
